<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ApplepayAfter $block */

use Laminas\Escaper\Escaper;
use Magento\Framework\View\Element\Template;
use Mollie\HyvaCheckout\Block\Checkout\Payment\ApplepayAfter;

?>
<div class="hidden">
    <script>
        function hideApplePayWhenNotAvailable() {
            if (!window.ApplePaySession || !window.ApplePaySession.canMakePayments()) {
                const applePayElement = document.getElementById('payment-method-option-mollie_methods_applepay');
                if (applePayElement) {
                    applePayElement.parentNode.removeChild(applePayElement);
                }
            }
        }

        hideApplePayWhenNotAvailable();

        window.addEventListener('magewire:update', () => {
            hideApplePayWhenNotAvailable();
        });
    </script>
    <?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>

    <?php if ($block->directIntegrationIsEnabled()): ?>
        <script>
            (() => {
                hyvaCheckout.api.after(() => {
                    const wire = () => {
                        return Magewire.find('checkout.payment.method.mollie_methods_applepay');
                    };

                    hyvaCheckout.payment.registerMethod({
                        code: 'mollie_methods_applepay',

                        method: {
                            validate: async function () {
                                return new Promise(resolve => {
                                    let session;

                                    let request = {
                                        countryCode: "<?php echo $escaper->escapeJs($block->getCountryId()); ?>",
                                        currencyCode: "<?php echo $escaper->escapeJs($block->getCurrencyCode()); ?>",
                                        supportedNetworks: <?php echo json_encode($block->getSupportedNetworks()); ?>,
                                        merchantCapabilities: ['supports3DS'],
                                        total: {
                                            label: "<?php echo $escaper->escapeJs($block->getStoreName()); ?>",
                                            amount: wire().amount
                                        },
                                    }

                                    if (!session) {
                                        session = new ApplePaySession(3, request);
                                    }

                                    session.onpaymentmethodselected = () => {
                                        session.completePaymentMethodSelection({
                                            label: 'Total',
                                            type: 'final',
                                            amount: wire().amount
                                        }, []);
                                    };

                                    session.onpaymentauthorized = (event) => {
                                        try {
                                            wire().setApplePayPaymentToken(JSON.stringify(event.payment.token)).then(() => {
                                                resolve(true);
                                            });
                                        } catch {
                                            session.completePayment(ApplePaySession.STATUS_ERROR);
                                            resolve(false);
                                        }
                                    };

                                    session.onvalidatemerchant = (event) => {
                                        window.fetch(
                                            "<?php echo $escaper->escapeUrl($block->getApplePayValidationUrl()); ?>",
                                            {
                                                method: 'POST',
                                                mode: 'cors',
                                                credentials: 'include',
                                                headers: {
                                                    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
                                                },
                                                body: 'validationURL=' + event.validationURL + '&form_key=' + hyva.getFormKey(),
                                            }
                                        )
                                            .then(response => response.json())
                                            .then(response => session.completeMerchantValidation(response))
                                            .catch(error => {
                                                console.error('Received error', error);
                                                hyvaCheckout.payment.dispatchExceptionMessage(
                                                    'Something went wrong, please check the logs for more information.'
                                                )
                                                session.abort();
                                                session = null;

                                                resolve(false);
                                            });
                                    };

                                    session.oncancel = () => {
                                        session = null;
                                        resolve(false);
                                    };

                                    session.begin();
                                });
                            }
                        }
                    });
                });
            })();
        </script>
        <?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
    <?php endif; ?>
</div>
