<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var WithTerminal $magewire */

use Magento\Framework\Escaper;
use Mollie\HyvaCheckout\Magewire\Checkout\Payment\Method\WithTerminal;


?>
<script>
    (() => {
        hyvaCheckout.api.after(() => {
            hyvaCheckout.payment.registerMethod({
                code: 'mollie_methods_pointofsale',

                method: {
                    validate: async function () {
                        if (document.querySelector('.mollie-no-terminal-found') !== null) {
                            hyvaCheckout.payment.dispatchExceptionMessage(
                                '<?= $escaper->escapeJs(__('No terminals found. Unable to place order using the Point Of Sale method.')) ?>',
                                'error'
                            );

                            window.scroll({ top: 0, behavior: 'smooth' });

                            return false;
                        }

                        return document.querySelectorAll('[name="mollie_selected_terminal"]:checked').length > 0;
                    }
                }
            })
        })
    })();
</script>
<?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
