<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Mollie\HyvaCheckout\Magewire\Checkout\Payment\Method\WithTerminal $magewire */
?>
<div>
    <?php if (count($magewire->getTerminals())): ?>
    <p class="font-bold"><?= $escaper->escapeHtml('Select a terminal:'); ?></p>
    <ul id="mollie-terminal-list">
        <?php foreach ($magewire->getTerminals() as $terminal): ?>
            <li>
                <label>
                    <input type="radio"
                           name="mollie_selected_terminal"
                           class="mr-2"
                           value="<?= $escaper->escapeHtmlAttr($terminal['id']); ?>"
                           wire:model="selectedTerminal"
                           required
                    />
                    <?= $escaper->escapehtml($terminal['brand']); ?>
                    <?= $escaper->escapehtml($terminal['model']); ?>
                    <?= $escaper->escapehtml($terminal['description']); ?>
                </label>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>

    <?php if ($magewire->getTerminals() === []): ?>
        <p class="mollie-no-terminal-found">
            <?= $escaper->escapeHtml('No terminals found. Unable to place order using the Point Of Sale method.'); ?>
        </p>
    <?php endif; ?>
</div>
