<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Mollie\HyvaCheckout\Magewire\Checkout\Payment\Method\ApplePay $magewire */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="mollie-applepay hidden" data-amount="<?php echo $magewire->amount; ?>">
    <?php if ($magewire->directIntegrationIsEnabled()): ?>
    <script>
        (() => {
            const registerValidation = () => {
                hyvaCheckout.validation.register(
                    'mollie_methods_applepay',
                    async () => new Promise(resolve => {
                        const component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');

                        const amount = document.querySelector('.mollie-applepay').dataset.amount;
                        let session;

                        let request = {
                            countryCode: "<?php echo $escaper->escapeJs($magewire->countryId); ?>",
                            currencyCode: "<?php echo $escaper->escapeJs($magewire->currencyCode); ?>",
                            supportedNetworks: <?php echo json_encode($magewire->getSupportedNetworks()); ?>,
                            merchantCapabilities: ['supports3DS'],
                            total: {
                                label: "<?php echo $escaper->escapeJs($magewire->storeName); ?>",
                                amount: amount
                            },
                        }

                        if (!session) {
                            session = new ApplePaySession(3, request);
                        }

                        session.onpaymentmethodselected = () => {
                            session.completePaymentMethodSelection({
                                label: 'Total',
                                type: 'final',
                                amount: amount
                            }, []);
                        };

                        session.onpaymentauthorized = (event) => {
                            try {
                                component.setApplePayPaymentToken(JSON.stringify(event.payment.token)).then(() => {
                                    resolve(true);
                                });
                            } catch {
                                session.completePayment(ApplePaySession.STATUS_ERROR);
                                resolve(false);
                            }
                        };

                        session.onvalidatemerchant = (event) => {
                            window.fetch(
                                "<?php echo $magewire->getApplePayValidationUrl(); ?>",
                                {
                                    method: 'POST',
                                    mode: 'cors',
                                    credentials: 'include',
                                    headers: {
                                        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
                                    },
                                    body: 'validationURL=' + event.validationURL + '&form_key=' + hyva.getFormKey(),
                                }
                            )
                                .then(response => response.json())
                                .then(response => session.completeMerchantValidation(response))
                                .catch(error => {
                                    console.error('Received error', error);
                                    hyvaCheckout.payment.dispatchExceptionMessage(
                                        'Something went wrong, please check the logs for more information.'
                                    )
                                    session.abort();
                                    session = null;

                                    resolve(false);
                                });
                        };

                        session.oncancel = () => {
                            session = null;
                            resolve(false);
                        };

                        session.begin();
                    }),
                    document.querySelector('.mollie-applepay'),
                    'payment'
                );
            };

            window.addEventListener('checkout:payment:method-activate', (event) => {
                registerValidation();

                document.querySelectorAll('.btn.btn-primary').forEach(element => {
                    if (event.detail.method === 'mollie_methods_applepay') {
                        element.classList.add('apple-pay-button');
                        element.classList.add('apple-pay-button-with-text');
                        element.classList.add('apple-pay-button-black-with-text');
                        return;
                    }

                    element.classList.remove('apple-pay-button');
                    element.classList.remove('apple-pay-button-with-text');
                    element.classList.remove('apple-pay-button-black-with-text');
                });
            });
        })();
    </script>
    <?php endif; ?>
</div>
