<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div>
<?php
/** @var Escaper $escaper */
/** @var CreditcardAfter $block */

use Magento\Framework\Escaper;
use Mollie\HyvaCheckout\Block\Checkout\Payment\CreditcardAfter;

if (!$block->isComponentsEnabled()) {
    return;
}
?>
<script>
    hyvaCheckout.api.after(() => {
        let mollie = null;
        let cardComponent = null;

        const wire = () => {
            return Magewire.find('checkout.payment.method.mollie_methods_creditcard');
        }

        hyvaCheckout.payment.registerMethod({
            code: 'mollie_methods_creditcard',

            method: {
                initialize: async function () {
                    if (mollie == null) {
                        mollie = await Mollie('<?= $escaper->escapeJs($block->getProfileId()) ?>', {
                            locale: '<?= $escaper->escapeJs($block->getLocale()); ?>',
                            testmode: <?= $escaper->escapeJs($block->isTestMode() ? 'true' : 'false') ?>,
                        });
                    }

                    if (cardComponent === null) {
                        cardComponent = mollie.createComponent('card', {
                            styles: {
                                base: {
                                    border: '1px solid #000',
                                },
                                invalid: {
                                    color: '#dc2626',
                                }
                            }
                        });
                    }

                    cardComponent.mount('#mollie-card-component');
                },

                uninitialize: async function () {
                    cardComponent.unmount();
                },

                validate: async function() {
                    let {token, error} = await mollie.createToken();
                    if (error) {
                        hyvaCheckout.payment.dispatchExceptionMessage(error.message)
                        return false;
                    }

                    await wire().setCardToken(token)
                    return true
                },
            }
        });
    });
</script>
<?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
