<?php
declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Mollie\HyvaCheckout\Magewire\Checkout\Payment\Method\WithTerminal $magewire */
?>
<div>
    <?php if (count($magewire->getTerminals())): ?>
    <p><?= $escaper->escapeHtml('Select a terminal:'); ?></p>
    <ul id="mollie-terminal-list">
        <?php foreach ($magewire->getTerminals() as $terminal): ?>
            <li>
                <label>
                    <input type="radio"
                           name="mollie_selected_terminal"
                           class="mr-2"
                           value="<?= $escaper->escapeHtmlAttr($terminal['id']); ?>"
                           wire:model="selectedTerminal"
                           required
                    />
                    <?= $escaper->escapehtml($terminal['brand']); ?>
                    <?= $escaper->escapehtml($terminal['model']); ?>
                    <?= $escaper->escapehtml($terminal['description']); ?>
                </label>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>

    <?php if (count($magewire->getTerminals())): ?>
        <p class="mollie-no-terminal-found">
            <?= $escaper->escapeHtml('No terminals found. Unable to place order using the Point Of Sale method.'); ?>
        </p>
    <?php endif; ?>

    <script>
        window.addEventListener('checkout:payment:method-activate', event => {
            if (event.detail.method !== 'mollie_methods_pointofsale') {
                return;
            }

            hyvaCheckout.payment.activate(
                'mollie_methods_pointofsale',
                {
                    validate() {
                        if (document.querySelector('.mollie-no-terminal-found') !== null) {
                            hyvaCheckout.payment.dispatchExceptionMessage(
                                <?= $escaper->escapeJs(__('No terminals found. Unable to place order using the Point Of Sale method.')) ?>
                            );
                            return false;
                        }

                        return document.querySelectorAll('[name="mollie_selected_terminal"]:checked').length > 0;
                    }
                },
                document.getElementById('mollie-terminal-list')
            );
        });
    </script>
</div>
