<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Mollie\HyvaCheckout\Magewire\Checkout\PointOfSaleWait $magewire */
?>

<div wire:poll.1s.keep-alive="fetchOrderStatus">
    <div><?= $escaper->escapeHtml(__('Order #%1', $magewire->incrementId)); ?></div>
    <div><?= $escaper->escapeHtml($magewire->currentStatus); ?></div>

    <?php if ($magewire->status == 'canceled'): ?>
        <button class="btn btn-primary mt-4" wire:click="retryOrder"><?= __('Retry'); ?></button>
    <?php endif; ?>

    <?php if ($magewire->status == 'processing'): ?>
        <?= $block->getChildHtml('loading') ?>
    <?php endif; ?>
</div>
